spring:
  datasource:
    url: jdbc:oracle:thin:@47.96.94.255:1521/qdh
    username: demo
    password: demo
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true

mybatis:
  type-aliases-package: com.nari.slsd.msrv.waterdiversion.model.po
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true

mapper:
  mappers:
    - com.nari.slsd.msrv.waterdiversion.mapper
  not-empty: false
  identity: oracle

msrv:
  uploadPath: ./file/
  isDayType: false
  imagePath: ./image/

logging:
  level:
    com.nari.slsd.msrv.waterdiversion.mapper: debug
    com.alibaba.nacos.client.config.impl: warn
  file:
    path: D:/log
  config: classpath:logback-spring.xml


dataType: oracle
