spring:
  datasource:
    url: jdbc:sqlserver://47.96.94.255:7134;DatabaseName=demo
    username: sa
    password: Nari@2008
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    max-active: 100 #连接池最大连接数（负值表示没有限制）
    max-wait: 3000 #连接池最大阻塞等待时间（负值表示没有限制）
    max-idle: 200 #连接池最大空闭连接数
    min-idle: 50 #连接汉最小空闲连接数
    timeout: 600 #连接超时时间（毫秒）

mybatis:
  type-aliases-package: com.nari.slsd.msrv.waterdiversion.model.po
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true

mapper:
  mappers:
    - com.nari.slsd.msrv.waterdiversion.mapper
  not-empty: false
  identity: sqlserver

msrv:
  uploadPath: ./file/
  isDayType: false
  imagePath: ./image/

logging:
  level:
    com.nari.slsd.msrv.waterdiversion.mapper: debug
    com.alibaba.nacos.client.config.impl: warn
  file:
    path: ./log
  config: classpath:logback-spring.xml

dataType: sqlserver2005
