spring:
  application:
    name: activiti
  devtools:
      restart:
        enabled: true
  datasource:
        #url: jdbc:mysql://localhost:3306/act?useUnicode=true&characterEncoding=UTF-8
        url: jdbc:mysql://47.104.134.222:3306/demo?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: yanjinghu
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  http:
      encoding:
        force: true
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8082
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
    type-aliases-package: com.nari.slsd.msrv.waterdiversion.model.po
    mapper-locations: classpath*:mapper/*.xml
    check-config-location: true

mapper:
    mappers:
      - com.nari.slsd.msrv.waterdiversion.mapper
    not-empty: true
    identity: mysql



msrv:
  uploadPath: ./file/
  isDayType: false
  imagePath: ./image/

logging:
  level:
    com.nari.slsd.msrv.waterdiversion.mapper: debug
    com.alibaba.nacos.client.config.impl: warn
  file:
    path: D:/log
  config: classpath:logback-spring.xml

dataType: mysql

